# SSH Credentials
ssh_host = "10.162.13.12"   # Replace with "129.187.44.36" if you want the no-VPN version
ssh_port = 22               # Port 443 if using without VPN
ssh_user = "societalcomputing"
ssh_password = "societalcomputing2024"

# Database Credentials
db_host = "127.0.0.1"       # The local bind address once SSH tunnel is established
db_port = 3306              # Default MariaDB/MySQL port, adjust if different
db_user = "aligniverse_team"
db_password = "equality$$"
db_name = "your_db_name"     # Replace with your actual database name
