ssh_host = '129.187.44.36'
ssh_port = 443
ssh_user = 'societalcomputing'
ssh_password = 'societalcomputing2024'

db_host = '127.0.0.1'
db_user = 'aligniverse_team'
db_password = 'equality$$'
db_name = 'deepfakes'
db_port = 3306

